//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenes
    {
        public Almacenes()
        {
            this.Pedidos = new HashSet<Pedidos>();
            this.Pedidos1 = new HashSet<Pedidos>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string CuentaContable { get; set; }
        public string Encargado { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Facsimil { get; set; }
        public string Observaciones { get; set; }
        public string DivisionID { get; set; }
        public string ARDivisionID { get; set; }
        public bool PermitirLotesCuarentenaPendiente { get; set; }
        public bool PermitirLotesCuarentenaAceptado { get; set; }
        public bool PermitirLotesCuarentenaRechazado { get; set; }
        public int DefaultUOMSalesDocs { get; set; }
    
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual ICollection<Pedidos> Pedidos1 { get; set; }
    }
}
