//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public Articulos()
        {
            this.ArticulosSuplidores = new HashSet<ArticulosSuplidores>();
            this.ArticulosSuplidores1 = new HashSet<ArticulosSuplidores>();
            this.Pedidos_Detalles = new HashSet<Pedidos_Detalles>();
            this.Articulos1 = new HashSet<Articulos>();
            this.Articulos11 = new HashSet<Articulos>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionLarga { get; set; }
        public string Tipo { get; set; }
        public string CodigoBarra { get; set; }
        public string Categoria { get; set; }
        public string SubCategoria { get; set; }
        public string UnidadCompra { get; set; }
        public string UnidadVenta { get; set; }
        public string UnidadReporte { get; set; }
        public decimal Costo { get; set; }
        public decimal CostoPromedio { get; set; }
        public bool Activo { get; set; }
        public string ClasificacionABC { get; set; }
        public decimal ConfiabilidadServicio { get; set; }
        public string Observaciones { get; set; }
        public bool Impuesto { get; set; }
        public string SuplidorPreferido { get; set; }
        public string FrecuenciaInventario { get; set; }
        public bool RequiereLote { get; set; }
        public Nullable<int> MultiploCompra { get; set; }
        public Nullable<int> MultiploVenta { get; set; }
        public short MetodoCosteo { get; set; }
        public decimal Peso { get; set; }
        public string UnidadPeso { get; set; }
        public string Familia { get; set; }
        public string Fabricante { get; set; }
        public decimal PrecioCompra { get; set; }
        public bool PermitirNegativos { get; set; }
        public string DescripcionCompras { get; set; }
        public bool Serializable { get; set; }
        public bool Assambly { get; set; }
        public string Photo { get; set; }
        public short QuantityDecimals { get; set; }
        public short AmountDecimals { get; set; }
        public decimal ComissionPercent { get; set; }
        public string TaxSchedule { get; set; }
        public string Reference { get; set; }
        public bool NonInventory { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Income_Account { get; set; }
        public string Inventory_Account { get; set; }
        public string Cost_Sales_Account { get; set; }
        public string Sales_Discount_Account { get; set; }
        public string Sales_Returns_Account { get; set; }
        public string Adjustments_Account { get; set; }
        public bool Commisionable { get; set; }
        public string OriginID { get; set; }
        public string ColorID { get; set; }
        public string SubFamilyID { get; set; }
        public string Presentation { get; set; }
        public decimal MaxQuantity { get; set; }
        public decimal MinQuantity { get; set; }
        public bool ProductionItem { get; set; }
        public bool SalesItem { get; set; }
        public bool Common { get; set; }
        public string ComissionLevelID { get; set; }
        public int WarrantyDays { get; set; }
        public string WarrantyCriteria { get; set; }
        public int WarrantyQuantity { get; set; }
        public string OfferID { get; set; }
        public bool Billable { get; set; }
        public string SubCostCenterID { get; set; }
        public string BrandID { get; set; }
        public float Height { get; set; }
        public float Width { get; set; }
        public string ProductionCostAccount { get; set; }
        public string BarUOID { get; set; }
        public bool CreateEquipmentRecord { get; set; }
        public bool ExigirDiasEntrega { get; set; }
        public bool ExigirDiasInstalacion { get; set; }
        public bool ExigirDiasGarantia { get; set; }
        public string PreviousID { get; set; }
        public decimal ProductionFactor { get; set; }
        public string ReportUOMID3 { get; set; }
        public string ManufacturerReference { get; set; }
        public string UOMPlanID { get; set; }
        public decimal FreightAmount { get; set; }
        public string PurchasesName { get; set; }
        public string AlternateName { get; set; }
        public string PlannerID { get; set; }
        public decimal Margin { get; set; }
        public bool DeductVendorComission { get; set; }
        public string BonusAccount { get; set; }
        public bool WarnIfNegativeOnQuote { get; set; }
        public decimal LandedCostFactor { get; set; }
        public bool PurchaseItem { get; set; }
        public string AttributeList1ID { get; set; }
        public string AttributeList2ID { get; set; }
        public bool RequiresItemLocations { get; set; }
        public string PurchaseAccountID { get; set; }
        public decimal ItemTaxAmount { get; set; }
        public string ItemTaxAccount { get; set; }
        public decimal ItemTaxPercent { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public int CreditSaleExpirationWarning { get; set; }
        public int CashSaleExpirationWarning { get; set; }
        public string Sales_Dispatchs_AccountID { get; set; }
        public string DocClassID { get; set; }
        public Nullable<int> CalculatePrices { get; set; }
        public string PurchasePriceCurrencyID { get; set; }
        public string WarehouseID { get; set; }
        public string EquivalentItemID { get; set; }
        public string EquivalentGroup { get; set; }
        public int QuarantineDays { get; set; }
        public bool ItemCubicaciones { get; set; }
        public bool ItemAvances { get; set; }
        public bool ItemRetenciones { get; set; }
        public bool AllowUseOnHold { get; set; }
        public decimal TechnicalComission { get; set; }
        public string CreatedBy { get; set; }
        public bool AllowChangeItemDescription { get; set; }
        public string OfferItemID { get; set; }
        public bool DontAllowReceptionsWithNoCost { get; set; }
        public decimal ManufacturingTolerance { get; set; }
        public decimal MaterialTolerance { get; set; }
        public decimal ManagerComissionPercent { get; set; }
        public Nullable<System.DateTime> PlacementDate { get; set; }
        public string UnitB_ID { get; set; }
        public bool IsSparePart { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public string TransitInventoryAccount { get; set; }
        public bool LotItemDuplicate { get; set; }
        public Nullable<decimal> CargoDevolucion { get; set; }
        public string CtaCostoContrato { get; set; }
        public string CtaCostoCompMenuda { get; set; }
        public string CtaCostoComision { get; set; }
        public string DevContrato { get; set; }
        public string DevCompMenuda { get; set; }
        public string DevComision { get; set; }
        public bool PublishAdmWebOrders { get; set; }
        public bool Contrato { get; set; }
    
        public virtual ICollection<ArticulosSuplidores> ArticulosSuplidores { get; set; }
        public virtual ICollection<ArticulosSuplidores> ArticulosSuplidores1 { get; set; }
        public virtual ICollection<Pedidos_Detalles> Pedidos_Detalles { get; set; }
        public virtual ICollection<Articulos> Articulos1 { get; set; }
        public virtual Articulos Articulos2 { get; set; }
        public virtual ICollection<Articulos> Articulos11 { get; set; }
        public virtual Articulos Articulos3 { get; set; }
    }
}
