//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosSuplidores
    {
        public int Contador { get; set; }
        public string Suplidor { get; set; }
        public string Articulo { get; set; }
        public string Referencia { get; set; }
        public decimal Precio1 { get; set; }
        public int DeliveryTime { get; set; }
        public decimal OfferQuantity { get; set; }
        public decimal Offer { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Articulos Articulos1 { get; set; }
    }
}
