//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Pedidos = new HashSet<Pedidos>();
            this.Pedidos1 = new HashSet<Pedidos>();
        }
    
        public string Codigo { get; set; }
        public string RazonSocial { get; set; }
        public string Contacto { get; set; }
        public string Cedula { get; set; }
        public bool Contrato { get; set; }
        public string Telefono { get; set; }
        public string Telefono2 { get; set; }
        public string Facsimil { get; set; }
        public string CorreoElectronico { get; set; }
        public string Territorio { get; set; }
        public string Tipo { get; set; }
        public decimal LimiteCredito { get; set; }
        public string Condiciones { get; set; }
        public string Observaciones { get; set; }
        public decimal MontoUltimaCompra { get; set; }
        public string NumeroRegistro { get; set; }
        public string Categoria { get; set; }
        public decimal Descuento { get; set; }
        public string Vendedor { get; set; }
        public string PaginaWeb { get; set; }
        public decimal Anticipos { get; set; }
        public decimal ChequesDevueltos { get; set; }
        public string Terminos { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int EmployeeQuantity { get; set; }
        public decimal CurrentVolume { get; set; }
        public decimal PotentialVolume { get; set; }
        public string Profile { get; set; }
        public bool Inactive { get; set; }
        public string CurrencyID { get; set; }
        public string PriceLevelID { get; set; }
        public string BillingContact { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public string Asistant { get; set; }
        public string Mobile { get; set; }
        public string Asistant_Phone { get; set; }
        public string GroupID { get; set; }
        public bool Prospect { get; set; }
        public string StatusID { get; set; }
        public string TypeID { get; set; }
        public string RecurringInvoiceID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> CancelationDate { get; set; }
        public string CancelationReasonID { get; set; }
        public string ReferenceID { get; set; }
        public string ARResponsible { get; set; }
        public string Owner { get; set; }
        public string Owner_SSN { get; set; }
        public decimal MaxSale { get; set; }
        public int InactiveDays { get; set; }
        public string LocationID { get; set; }
        public string InstallationCode { get; set; }
        public string StateID { get; set; }
        public string SectorID { get; set; }
        public string SubClassID { get; set; }
        public string ShipToAddressID { get; set; }
        public string BillToAddressID { get; set; }
        public string TaxScheduleID { get; set; }
        public string ComissionLevelID { get; set; }
        public string ManagementComissionLevelID { get; set; }
        public string VendorID { get; set; }
        public int Gender { get; set; }
        public string RegionID { get; set; }
        public string ComercialName { get; set; }
        public bool GenerateNCF { get; set; }
        public int NCF_Sequence { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public Nullable<System.DateTime> FechaInactivo { get; set; }
        public string CustomInvoiceFormat { get; set; }
        public bool RequireQuoteOnService { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToCityID { get; set; }
        public string ShipToStateID { get; set; }
        public string ShipToCountryID { get; set; }
        public string ShipToPhone1 { get; set; }
        public string ShipToPhone2 { get; set; }
        public string ShipToFax { get; set; }
        public string ShipToContact { get; set; }
        public string BillToAddress { get; set; }
        public string BillToCityID { get; set; }
        public string BillToStateID { get; set; }
        public string BillToCountryID { get; set; }
        public string BillToPhone1 { get; set; }
        public string BillToPhone2 { get; set; }
        public string BillToFax { get; set; }
        public string BillToContact { get; set; }
        public bool Legal { get; set; }
        public string Repartidor { get; set; }
        public string BusinessActivity { get; set; }
        public bool VisitDay1 { get; set; }
        public bool VisitDay2 { get; set; }
        public bool VisitDay3 { get; set; }
        public bool VisitDay4 { get; set; }
        public bool VisitDay5 { get; set; }
        public bool VisitDay6 { get; set; }
        public bool VisitDay7 { get; set; }
        public string Role { get; set; }
        public bool DontAllowServiceRequests { get; set; }
        public string TechnicalContactEMail { get; set; }
        public string CreatedBy { get; set; }
        public int ContactInterval { get; set; }
        public bool ISCustomer { get; set; }
        public bool ISPromoContact { get; set; }
        public bool Visitday8 { get; set; }
        public bool Visitday9 { get; set; }
        public short Visitweek { get; set; }
        public bool IsEmployee { get; set; }
        public string UnitB_ID { get; set; }
        public string Empleado { get; set; }
        public bool Week1 { get; set; }
        public bool Week2 { get; set; }
        public bool Week3 { get; set; }
        public bool Week4 { get; set; }
        public bool Week5 { get; set; }
        public bool PersonaFisica { get; set; }
        public string Pais { get; set; }
        public string ZonaGeografica { get; set; }
        public string NoImportacion { get; set; }
        public string IdentificadorFiscal { get; set; }
        public bool PublishAdmWebOrders { get; set; }
        public string AdmWebOrdersPassword { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual Terminos Terminos1 { get; set; }
        public virtual Empleados Empleados1 { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual Empleados Empleados2 { get; set; }
        public virtual ICollection<Pedidos> Pedidos1 { get; set; }
    }
}
