//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public Empleados()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Clientes1 = new HashSet<Clientes>();
            this.Clientes2 = new HashSet<Clientes>();
            this.Pedidos = new HashSet<Pedidos>();
            this.Empleados1 = new HashSet<Empleados>();
        }
    
        public string Codigo { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public bool Activo { get; set; }
        public string Cedula { get; set; }
        public string Telefono { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Celular { get; set; }
        public string Beeper { get; set; }
        public string Nacionalidad { get; set; }
        public string Sexo { get; set; }
        public bool Pensionado { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<short> EstadoCivil { get; set; }
        public string NombreConyugue { get; set; }
        public string NumeroDependientes { get; set; }
        public string LugarNacimiento { get; set; }
        public string Tipo { get; set; }
        public string Direccion { get; set; }
        public string Sector { get; set; }
        public string Ciudad { get; set; }
        public string Provincia { get; set; }
        public string CodigoPostal { get; set; }
        public string Pais { get; set; }
        public string DireccionTemporal { get; set; }
        public string SectorTemporal { get; set; }
        public string CiudadTemporal { get; set; }
        public string ProvinciaTemporal { get; set; }
        public string CodigoPostalTemporal { get; set; }
        public string PaisTemporal { get; set; }
        public string Posicion { get; set; }
        public string Departamento { get; set; }
        public string Sucursal { get; set; }
        public string Categoria { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public bool Vendedor { get; set; }
        public bool DescontarSeguro { get; set; }
        public decimal Salario { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public string NoAfiliacion { get; set; }
        public string CuentaBancaria { get; set; }
        public Nullable<short> MetodoPago { get; set; }
        public Nullable<short> FrecuenciaPago { get; set; }
        public string NivelComision { get; set; }
        public Nullable<System.DateTime> VacacionesFecha { get; set; }
        public short VacacionesDias { get; set; }
        public short VacacionesTomados { get; set; }
        public short VacacionesPendientes { get; set; }
        public string Observaciones { get; set; }
        public string Foto { get; set; }
        public string Personalizado1 { get; set; }
        public string Personalizado2 { get; set; }
        public string Personalizado3 { get; set; }
        public string Personalizado4 { get; set; }
        public string Personalizado5 { get; set; }
        public int Acumulated_Periods { get; set; }
        public decimal Acumulated_Salary { get; set; }
        public decimal Acumulated_Tax { get; set; }
        public bool ARS { get; set; }
        public bool AFP { get; set; }
        public bool Laboral_Risk { get; set; }
        public decimal Acumulated_Income { get; set; }
        public string ComisionPayablesAccount { get; set; }
        public string ComisionExpenseAccount { get; set; }
        public decimal ComissionPercent { get; set; }
        public string Initials { get; set; }
        public decimal HourFee { get; set; }
        public string Segment1 { get; set; }
        public string Segment2 { get; set; }
        public string PayablesAccount { get; set; }
        public string Segment0 { get; set; }
        public string ReceivablesAccount { get; set; }
        public string SegmentCompany { get; set; }
        public string Segment1_Liability { get; set; }
        public string Segment1_Expense { get; set; }
        public string Segment2_Liability { get; set; }
        public string Segment2_Expense { get; set; }
        public string Bank { get; set; }
        public int PaymentMethod { get; set; }
        public string StateID { get; set; }
        public string TerritoryID { get; set; }
        public string Account { get; set; }
        public string BankAccountID { get; set; }
        public int ProductionComissionCalculation { get; set; }
        public decimal ProductionFactor { get; set; }
        public decimal HourCost { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public bool Tecnitian { get; set; }
        public string Email { get; set; }
        public string CreatedBy { get; set; }
        public string SupervisorID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> CreatedHour { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> EditHour { get; set; }
        public decimal Acumulate_Tax { get; set; }
        public bool ISR { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int LastPayrollMonth { get; set; }
        public int LastPayrollYear { get; set; }
        public decimal Acumulated_OtherIncome { get; set; }
        public Nullable<int> ARS_Periodo { get; set; }
        public Nullable<int> AFP_Periodo { get; set; }
        public Nullable<int> ISR_Periodo { get; set; }
        public string ShiftID { get; set; }
        public string TipoNomina { get; set; }
        public Nullable<System.DateTime> VacacionesInicio { get; set; }
        public Nullable<System.DateTime> VacacionesFinal { get; set; }
        public string CorreoElectronico { get; set; }
        public bool Delivery { get; set; }
        public string CentroCosto { get; set; }
        public string Estado_ID { get; set; }
        public string EmergenciaApellidos { get; set; }
        public string EmergenciaNombres { get; set; }
        public string EmergenciaParentesco { get; set; }
        public string EmergenciaTelefono { get; set; }
        public string TipoSangre { get; set; }
        public string Alergias { get; set; }
        public Nullable<decimal> HorasCorrientes { get; set; }
        public Nullable<decimal> HorasExtras { get; set; }
        public Nullable<decimal> HorasEspeciales { get; set; }
        public Nullable<decimal> HorasNocturnas { get; set; }
        public Nullable<bool> Manteinance { get; set; }
        public Nullable<bool> Manufactura { get; set; }
        public string DivisionID { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Clientes> Clientes1 { get; set; }
        public virtual ICollection<Clientes> Clientes2 { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual ICollection<Empleados> Empleados1 { get; set; }
        public virtual Empleados Empleados2 { get; set; }
    }
}
