//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposImpuestos_Impuestos
    {
        public int Contador { get; set; }
        public string GrupoImpuesto { get; set; }
        public string Impuesto { get; set; }
    }
}
