//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOISESEntities : DbContext
    {
        public MOISESEntities()
            : base("name=MOISESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Almacenes> Almacenes { get; set; }
        public DbSet<Articulos> Articulos { get; set; }
        public DbSet<ArticulosSuplidores> ArticulosSuplidores { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Empleados> Empleados { get; set; }
        public DbSet<GruposImpuestos_Impuestos> GruposImpuestos_Impuestos { get; set; }
        public DbSet<Monedas> Monedas { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<Pedidos_Detalles> Pedidos_Detalles { get; set; }
        public DbSet<Terminos> Terminos { get; set; }
    }
}
