//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monedas
    {
        public Monedas()
        {
            this.Clientes = new HashSet<Clientes>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal TasaCambio { get; set; }
        public string CuentaAjustes { get; set; }
        public string Observaciones { get; set; }
        public string Sign { get; set; }
        public string RoundingsAccount { get; set; }
        public string AdjustmentsDivisionID { get; set; }
        public string RoundingsDivisionID { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}
