//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos_Detalles
    {
        public int Contador { get; set; }
        public int Numero { get; set; }
        public short Renglon { get; set; }
        public string Articulo { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public decimal Descuento { get; set; }
        public decimal Cantidad { get; set; }
        public decimal CantidadVendida { get; set; }
        public string Unidad { get; set; }
        public short RenglonCombo { get; set; }
        public decimal MontoImpuesto { get; set; }
        public string Proyecto { get; set; }
        public string CostCenter { get; set; }
        public string Lot { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public string ParameterUOM { get; set; }
        public bool IsPromo { get; set; }
        public Nullable<System.DateTime> FechaPromesa { get; set; }
        public float Parameter1Quantity { get; set; }
        public float Parameter2Quantity { get; set; }
        public bool Closed { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public decimal ItemTaxAmount { get; set; }
        public bool Status { get; set; }
        public bool Tax { get; set; }
        public decimal DiscountAmount { get; set; }
        public string TaxSchedule { get; set; }
        public Nullable<System.DateTime> DateReject { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
