//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminos
    {
        public Terminos()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public short Dias { get; set; }
        public short DiasBloqueo { get; set; }
        public short DiasDescuento { get; set; }
        public decimal PorcientoDescuento { get; set; }
        public string Observaciones { get; set; }
        public int DiscountDays2 { get; set; }
        public decimal DiscountPercent2 { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
